### ISSUE TITLE
Images manquantes

### ISSUE THREAD

**Issue by regelo** [lzrdkng/Poly-Public#1]
Le code de `howto.tex` inclus plusieurs images, mais ces images ne sont pas dans le dépôt GitHub. Ces images sont appelées dans le fichier : 

- bash_1
- bash_2
- bash_ls
- bash_ls_2
- bash_cd
- bash_rm
- grep

**Comment by lzrdkng** [comment]
Merci de la remarque. Les images sont maintenant mises dans le dossier ./Linux/img/
