### ISSUE TITLE
Gestion des accents français

### ISSUE THREAD

**Issue by regelo** [lzrdkng/Poly-Public#5]
Les accents français ne s'affichent pas bien dans le fichier généré sur Linux. Cela peut être réglé en utilisant les codes de LaTeX (ex.: \'{e} pour é) ou bien en spécifiant l'encodage du fichier (avec \usepackage[utf8]{inputenc} je crois). Je ne sais pas quelle approche vous préféreriez, alors j'ai préféré demander.

**Comment by lzrdkng** [comment]
Le package **utf8** a été ajouté à _packages.tex_, bien vu.
